-- RUNSQLSTM SRCFILE(CJB4033071/QSQLSRC) SRCMBR(SCRPER)
CREATE TABLE CJB4033071.PERSONA (
    IDEPER  CHAR(18) NOT NULL,
    NOMPER  CHAR(40) NOT NULL,
    EDAPER  SMALLINT NOT NULL,
    GENPER  CHAR(1) DEFAULT 'X' NOT NULL,
    CONSTRAINT PERSONA_PRIMARY_KEY PRIMARY KEY (IDEPER),
    CONSTRAINT PERSONA_GENPER CHECK(GENPER IN ('M', 'F', 'X'))
)
RCDFMT RPERSONA;

-- LABEL; Nombre personalizado tabla
LABEL ON TABLE CJB4033071.PERSONA IS 'DATOS DE PERSONA';

-- LABEL; Encabezado personalizado
LABEL ON COLUMN CJB4033071.PERSONA (
    IDEPER TEXT IS 'IDENTIDAD PERSONA',
    NOMPER TEXT IS 'NOMBRE',
    EDAPER TEXT IS 'EDAD',
    GENPER TEXT IS 'GENERO'
);

--COMENTARIO; Descripcion tecnica
COMMENT ON COLUMN CJB4033071.PERSONA (
    IDEPER IS 'NUMERO DE IDENTIDAD PERSONA',
    NOMPER IS 'NOMBRE COMPLETO PERSONA',
    EDAPER IS 'EDAD DE LA PERSONA',
    GENPER IS 'GENERO M = MASCULINO, F = FEMENINO Y X = SIN ESPECIFICAR'
);

-- --============================================================================================

CREATE TABLE CJB4033071.PERDIR (
    IDDIRE INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    IDEPER CHAR(18) NOT NULL,
    TIPDIR CHAR(1) DEFAULT 'O' NOT NULL,
    CALLE  VARCHAR(100),
    CIUDAD VARCHAR(50),
    DEPART VARCHAR(50),
    PAIS   VARCHAR(50),
    CONSTRAINT PERDIR_PRIMARY_KEY PRIMARY KEY (IDDIRE),
    CONSTRAINT PERDIR_FOREIGN_KEY FOREIGN KEY (IDEPER)
        REFERENCES CJB4033071.PERSONA(IDEPER),
    CONSTRAINT PERDIR_TIPDIR CHECK(TIPDIR IN ('R', 'T', 'O'))
)
RCDFMT RPERDIR;

-- LABEL; Nombre personalizado tabla
LABEL ON TABLE CJB4033071.PERDIR IS 'DIRECCION DE PERSONA';

-- LABEL; Encabezado personalizado
LABEL ON COLUMN CJB4033071.PERDIR (
    IDDIRE TEXT IS 'ID DIRECCION',
    IDEPER TEXT IS 'IDENTIDAD PERSONA',
    TIPDIR TEXT IS 'TIPO DE DIRECCION',
    CALLE  TEXT IS 'CALLE',
    CIUDAD TEXT IS 'CIUDAD',
    DEPART TEXT IS 'DEPARTAMENTO',
    PAIS   TEXT IS 'PAIS'
);

--COMENTARIO; Descripcion tecnica
COMMENT ON COLUMN CJB4033071.PERDIR (
    IDDIRE IS 'ID UNICO DE DIRECCION',
    IDEPER IS 'NUMERO DE IDENTIDAD PERSONA',
    TIPDIR IS 'TIPO DE DIRECCION R=RESIDENCIAL, T=TRABAJO, O=OTRO',
    CALLE  IS 'CALLE',
    CIUDAD IS 'CIUDAD',
    DEPART IS 'DEPARTAMENTO',
    PAIS   IS 'PAIS'
);

-- --==========================================================================

CREATE TABLE CJB4033071.PEREDU (
    IDEDUC INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    IDEPER CHAR(18) NOT NULL,
    NIVEDU CHAR(1), --P=PRIMARIA, S=SECUNDARIA, U=UNIVERSIDAD, P=POSTGRADO, D=DOCTORADO
    INSTIT VARCHAR(100),
    ANIINI INT,
    ANIFIN INT,
    CONSTRAINT PEREDU_PRIMARY_KEY PRIMARY KEY (IDEDUC),
    CONSTRAINT PEREDU_FOREIGN_KEY FOREIGN KEY (IDEPER)
        REFERENCES CJB4033071.PERSONA(IDEPER),
    CONSTRAINT PEREDU_NIVEDU CHECK(NIVEDU IN ('P', 'S', 'U', 'P', 'D'))
)
RCDFMT RPEREDU;

-- LABEL; Nombre personalizado tabla
LABEL ON TABLE CJB4033071.PEREDU IS 'EDUCACION DE PERSONA';

-- LABEL; Encabezado personalizado
LABEL ON COLUMN CJB4033071.PEREDU (
    IDEDUC TEXT IS 'ID EDUCACION',
    IDEPER TEXT IS 'IDENTIDAD PERSONA',
    NIVEDU TEXT IS 'NIVEL EDUCATIVO',
    INSTIT TEXT IS 'INSTITUCION',
    ANIINI TEXT IS 'ANIO DE INICIO',
    ANIFIN TEXT IS 'ANIO DE FINALIZACION'
);

--COMENTARIO; Descripcion tecnica
COMMENT ON COLUMN CJB4033071.PEREDU (
    IDEDUC IS 'ID UNICO DE EDUCACION',
    IDEPER IS 'NUMERO DE IDENTIDAD PERSONA',
    NIVEDU IS 'NIVEDU P=PRIMARIA, S=SECUN.., U=UNI.., P=POSTGR.., D=DOCTORA..',
    INSTIT IS 'INSTITUTO DE ESTUDIO',
    ANIINI IS 'ANIO DE INICIO',
    ANIFIN IS 'ANIO DE FINALIZACION'
);
